server.port=8080
spring.application.name=starwars-backend

# SWAPI URL configuration
swapi.films.url=https://swapi.dev/api/films/

# Actuator endpoints
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

